"""
Turn structured adverse-impact results into a readable audit narrative.

- deterministic_summary(): always available, rule-based, zero dependencies on
  any LLM. This is what guarantees the tool is useful with no API key.
- llm_narrative(): an optional richer, plain-English narrative for stakeholders,
  generated by whatever provider is configured in src/llm.py.
"""
from __future__ import annotations

from . import llm
from .adverse_impact import AttributeResult

SYSTEM = (
    "You are a careful, neutral fairness analyst supporting an enterprise Talent "
    "team. You explain adverse-impact (four-fifths rule) results to non-technical "
    "HR and Legal stakeholders. Be precise and measured. A four-fifths flag is a "
    "trigger for review, never a finding of illegal discrimination. Always note "
    "that job-relatedness and business-necessity can justify a disparity, and that "
    "this is a screening aid, not legal advice. Do not invent numbers."
)


def _fmt_pct(x: float) -> str:
    return f"{x * 100:.1f}%"


def deterministic_summary(results: list[AttributeResult]) -> str:
    """Rule-based markdown summary that always works (no LLM required)."""
    lines: list[str] = ["## Adverse-impact summary\n"]
    flagged = [r for r in results if r.any_flag]

    if not flagged:
        lines.append(
            "No protected attribute fell below the 0.80 four-fifths threshold in "
            "this dataset. Continue routine monitoring; re-run as new data arrives."
        )
    else:
        attrs = ", ".join(r.attribute for r in flagged)
        lines.append(
            f"**{len(flagged)} attribute(s) flagged** for potential adverse "
            f"impact: {attrs}. Details below."
        )

    for r in results:
        lines.append(f"\n### {r.attribute}  (outcome: `{r.outcome}`)")
        if not r.groups:
            lines.append("- No groups met the minimum sample size.")
            continue
        ref = next((g for g in r.groups if g.is_reference), None)
        if ref:
            lines.append(
                f"- Reference (highest-rate) group: **{ref.group}** at "
                f"{_fmt_pct(ref.selection_rate)} selection rate "
                f"({ref.selected}/{ref.n})."
            )
        for g in r.groups:
            if g.is_reference:
                continue
            bits = [
                f"- **{g.group}**: {_fmt_pct(g.selection_rate)} "
                f"({g.selected}/{g.n}), impact ratio "
                f"**{g.impact_ratio:.2f}**"
            ]
            if g.four_fifths_flag:
                bits.append(" \u2014 \u26a0\ufe0f below 0.80 four-fifths threshold")
                if g.p_value is not None:
                    sig = "statistically significant" if g.significant else "not statistically significant"
                    bits.append(f" (p={g.p_value:.3f}, {sig})")
            if g.small_sample:
                bits.append(" \u2014 note: small sample (N<30), interpret with caution")
            lines.append("".join(bits))

    lines.append(
        "\n---\n*Screening aid only \u2014 not legal advice and not a compliance "
        "certification. A flag warrants review of job-relatedness and "
        "less-discriminatory alternatives; partner with Legal.*"
    )
    return "\n".join(lines)


def _facts_block(results: list[AttributeResult]) -> str:
    out: list[str] = []
    for r in results:
        out.append(f"Attribute: {r.attribute} | outcome: {r.outcome} | "
                   f"reference group: {r.reference_group}")
        for g in r.groups:
            out.append(
                f"  - {g.group}: n={g.n}, selected={g.selected}, "
                f"rate={g.selection_rate:.4f}, impact_ratio={g.impact_ratio:.4f}, "
                f"four_fifths_flag={g.four_fifths_flag}, "
                f"p_value={'NA' if g.p_value is None else round(g.p_value, 4)}, "
                f"significant={g.significant}, small_sample={g.small_sample}"
            )
    return "\n".join(out)


def llm_narrative(results: list[AttributeResult]) -> str | None:
    """Optional richer narrative. Returns None if no provider is configured."""
    if not llm.is_configured():
        return None
    prompt = (
        "Here are computed adverse-impact results from a hiring dataset. Write a "
        "concise, plain-English audit narrative (250-400 words) for HR and Legal "
        "stakeholders. Cover: what was found, which groups are flagged and how "
        "serious (consider both the impact ratio and statistical significance and "
        "sample size), the key caveats (flag != illegal; job-relatedness defense), "
        "and 3-5 concrete recommended next steps. Do not invent numbers beyond "
        "those given.\n\nRESULTS:\n" + _facts_block(results)
    )
    return llm.complete(SYSTEM, prompt)
